import * as SamanthaShawnEngagement5jpg from './Samantha + Shawn Engagement-5.jpg';
import * as SamanthaShawnEngagement50jpg from './Samantha + Shawn Engagement-50.jpg';
import * as SamanthaShawnEngagement51jpg from './Samantha + Shawn Engagement-51.jpg';
import * as SamanthaShawnEngagement52jpg from './Samantha + Shawn Engagement-52.jpg';
import * as SamanthaShawnEngagement53jpg from './Samantha + Shawn Engagement-53.jpg';
import * as SamanthaShawnEngagement54jpg from './Samantha + Shawn Engagement-54.jpg';
import * as SamanthaShawnEngagement55jpg from './Samantha + Shawn Engagement-55.jpg';
import * as SamanthaShawnEngagement56jpg from './Samantha + Shawn Engagement-56.jpg';
import * as SamanthaShawnEngagement57jpg from './Samantha + Shawn Engagement-57.jpg';
import * as SamanthaShawnEngagement58jpg from './Samantha + Shawn Engagement-58.jpg';
import * as SamanthaShawnEngagement59jpg from './Samantha + Shawn Engagement-59.jpg';
import * as SamanthaShawnEngagement6jpg from './Samantha + Shawn Engagement-6.jpg';
import * as SamanthaShawnEngagement60jpg from './Samantha + Shawn Engagement-60.jpg';
import * as SamanthaShawnEngagement61jpg from './Samantha + Shawn Engagement-61.jpg';
import * as SamanthaShawnEngagement62jpg from './Samantha + Shawn Engagement-62.jpg';
import * as SamanthaShawnEngagement63jpg from './Samantha + Shawn Engagement-63.jpg';
import * as SamanthaShawnEngagement65jpg from './Samantha + Shawn Engagement-65.jpg';
import * as SamanthaShawnEngagement66jpg from './Samantha + Shawn Engagement-66.jpg';
import * as SamanthaShawnEngagement67jpg from './Samantha + Shawn Engagement-67.jpg';
import * as SamanthaShawnEngagement68jpg from './Samantha + Shawn Engagement-68.jpg';
import * as SamanthaShawnEngagement69jpg from './Samantha + Shawn Engagement-69.jpg';
import * as SamanthaShawnEngagement7jpg from './Samantha + Shawn Engagement-7.jpg';
import * as SamanthaShawnEngagement70jpg from './Samantha + Shawn Engagement-70.jpg';
import * as SamanthaShawnEngagement71jpg from './Samantha + Shawn Engagement-71.jpg';
import * as SamanthaShawnEngagement72jpg from './Samantha + Shawn Engagement-72.jpg';
import * as SamanthaShawnEngagement73jpg from './Samantha + Shawn Engagement-73.jpg';
import * as SamanthaShawnEngagement74jpg from './Samantha + Shawn Engagement-74.jpg';
import * as SamanthaShawnEngagement75jpg from './Samantha + Shawn Engagement-75.jpg';
import * as SamanthaShawnEngagement76jpg from './Samantha + Shawn Engagement-76.jpg';
import * as SamanthaShawnEngagement77jpg from './Samantha + Shawn Engagement-77.jpg';
import * as SamanthaShawnEngagement78jpg from './Samantha + Shawn Engagement-78.jpg';
import * as SamanthaShawnEngagement79jpg from './Samantha + Shawn Engagement-79.jpg';
import * as SamanthaShawnEngagement8jpg from './Samantha + Shawn Engagement-8.jpg';
import * as SamanthaShawnEngagement80jpg from './Samantha + Shawn Engagement-80.jpg';
import * as SamanthaShawnEngagement81jpg from './Samantha + Shawn Engagement-81.jpg';
import * as SamanthaShawnEngagement82jpg from './Samantha + Shawn Engagement-82.jpg';
import * as SamanthaShawnEngagement83jpg from './Samantha + Shawn Engagement-83.jpg';
import * as SamanthaShawnEngagement84jpg from './Samantha + Shawn Engagement-84.jpg';
import * as SamanthaShawnEngagement85jpg from './Samantha + Shawn Engagement-85.jpg';
import * as SamanthaShawnEngagement86jpg from './Samantha + Shawn Engagement-86.jpg';
import * as SamanthaShawnEngagement87jpg from './Samantha + Shawn Engagement-87.jpg';
import * as SamanthaShawnEngagement88jpg from './Samantha + Shawn Engagement-88.jpg';
import * as SamanthaShawnEngagement89jpg from './Samantha + Shawn Engagement-89.jpg';
import * as SamanthaShawnEngagement9jpg from './Samantha + Shawn Engagement-9.jpg';
import * as SamanthaShawnEngagement90jpg from './Samantha + Shawn Engagement-90.jpg';
import * as SamanthaShawnEngagement91jpg from './Samantha + Shawn Engagement-91.jpg';
import * as SamanthaShawnEngagement92jpg from './Samantha + Shawn Engagement-92.jpg';
import * as SamanthaShawnEngagement93jpg from './Samantha + Shawn Engagement-93.jpg';
import * as SamanthaShawnEngagement94jpg from './Samantha + Shawn Engagement-94.jpg';
import * as SamanthaShawnEngagement96jpg from './Samantha + Shawn Engagement-96.jpg';
import * as SamanthaShawnEngagement97jpg from './Samantha + Shawn Engagement-97.jpg';
import * as SamanthaShawnEngagement98jpg from './Samantha + Shawn Engagement-98.jpg';

/**
 * Collection of engagement photos
 */
export const EngagementPhotos: { [key: string]: { src: string; height: number; width: number } } = {
    SamanthaShawnEngagement5jpg: { src: SamanthaShawnEngagement5jpg, height: 500, width: 333 },
    SamanthaShawnEngagement50jpg: { src: SamanthaShawnEngagement50jpg, height: 500, width: 749 },
    SamanthaShawnEngagement51jpg: { src: SamanthaShawnEngagement51jpg, height: 500, width: 749 },
    SamanthaShawnEngagement52jpg: { src: SamanthaShawnEngagement52jpg, height: 500, width: 749 },
    SamanthaShawnEngagement53jpg: { src: SamanthaShawnEngagement53jpg, height: 500, width: 749 },
    SamanthaShawnEngagement54jpg: { src: SamanthaShawnEngagement54jpg, height: 500, width: 749 },
    SamanthaShawnEngagement55jpg: { src: SamanthaShawnEngagement55jpg, height: 500, width: 749 },
    SamanthaShawnEngagement56jpg: { src: SamanthaShawnEngagement56jpg, height: 500, width: 749 },
    SamanthaShawnEngagement57jpg: { src: SamanthaShawnEngagement57jpg, height: 500, width: 749 },
    SamanthaShawnEngagement58jpg: { src: SamanthaShawnEngagement58jpg, height: 500, width: 333 },
    SamanthaShawnEngagement59jpg: { src: SamanthaShawnEngagement59jpg, height: 500, width: 333 },
    SamanthaShawnEngagement6jpg: { src: SamanthaShawnEngagement6jpg, height: 500, width: 749 },
    SamanthaShawnEngagement60jpg: { src: SamanthaShawnEngagement60jpg, height: 500, width: 333 },
    SamanthaShawnEngagement61jpg: { src: SamanthaShawnEngagement61jpg, height: 500, width: 333 },
    SamanthaShawnEngagement62jpg: { src: SamanthaShawnEngagement62jpg, height: 500, width: 333 },
    SamanthaShawnEngagement63jpg: { src: SamanthaShawnEngagement63jpg, height: 500, width: 333 },
    SamanthaShawnEngagement65jpg: { src: SamanthaShawnEngagement65jpg, height: 500, width: 333 },
    SamanthaShawnEngagement66jpg: { src: SamanthaShawnEngagement66jpg, height: 500, width: 749 },
    SamanthaShawnEngagement67jpg: { src: SamanthaShawnEngagement67jpg, height: 500, width: 749 },
    SamanthaShawnEngagement68jpg: { src: SamanthaShawnEngagement68jpg, height: 500, width: 749 },
    SamanthaShawnEngagement69jpg: { src: SamanthaShawnEngagement69jpg, height: 500, width: 749 },
    SamanthaShawnEngagement7jpg: { src: SamanthaShawnEngagement7jpg, height: 500, width: 749 },
    SamanthaShawnEngagement70jpg: { src: SamanthaShawnEngagement70jpg, height: 500, width: 749 },
    SamanthaShawnEngagement71jpg: { src: SamanthaShawnEngagement71jpg, height: 500, width: 749 },
    SamanthaShawnEngagement72jpg: { src: SamanthaShawnEngagement72jpg, height: 500, width: 749 },
    SamanthaShawnEngagement73jpg: { src: SamanthaShawnEngagement73jpg, height: 500, width: 749 },
    SamanthaShawnEngagement74jpg: { src: SamanthaShawnEngagement74jpg, height: 500, width: 749 },
    SamanthaShawnEngagement75jpg: { src: SamanthaShawnEngagement75jpg, height: 500, width: 749 },
    SamanthaShawnEngagement76jpg: { src: SamanthaShawnEngagement76jpg, height: 500, width: 333 },
    SamanthaShawnEngagement77jpg: { src: SamanthaShawnEngagement77jpg, height: 500, width: 333 },
    SamanthaShawnEngagement78jpg: { src: SamanthaShawnEngagement78jpg, height: 500, width: 333 },
    SamanthaShawnEngagement79jpg: { src: SamanthaShawnEngagement79jpg, height: 500, width: 333 },
    SamanthaShawnEngagement8jpg: { src: SamanthaShawnEngagement8jpg, height: 500, width: 749 },
    SamanthaShawnEngagement80jpg: { src: SamanthaShawnEngagement80jpg, height: 500, width: 333 },
    SamanthaShawnEngagement81jpg: { src: SamanthaShawnEngagement81jpg, height: 500, width: 333 },
    SamanthaShawnEngagement82jpg: { src: SamanthaShawnEngagement82jpg, height: 500, width: 749 },
    SamanthaShawnEngagement83jpg: { src: SamanthaShawnEngagement83jpg, height: 500, width: 749 },
    SamanthaShawnEngagement84jpg: { src: SamanthaShawnEngagement84jpg, height: 500, width: 749 },
    SamanthaShawnEngagement85jpg: { src: SamanthaShawnEngagement85jpg, height: 500, width: 749 },
    SamanthaShawnEngagement86jpg: { src: SamanthaShawnEngagement86jpg, height: 500, width: 749 },
    SamanthaShawnEngagement87jpg: { src: SamanthaShawnEngagement87jpg, height: 500, width: 749 },
    SamanthaShawnEngagement88jpg: { src: SamanthaShawnEngagement88jpg, height: 500, width: 749 },
    SamanthaShawnEngagement89jpg: { src: SamanthaShawnEngagement89jpg, height: 500, width: 749 },
    SamanthaShawnEngagement9jpg: { src: SamanthaShawnEngagement9jpg, height: 500, width: 333 },
    SamanthaShawnEngagement90jpg: { src: SamanthaShawnEngagement90jpg, height: 500, width: 749 },
    SamanthaShawnEngagement91jpg: { src: SamanthaShawnEngagement91jpg, height: 500, width: 749 },
    SamanthaShawnEngagement92jpg: { src: SamanthaShawnEngagement92jpg, height: 500, width: 333 },
    SamanthaShawnEngagement93jpg: { src: SamanthaShawnEngagement93jpg, height: 500, width: 333 },
    SamanthaShawnEngagement94jpg: { src: SamanthaShawnEngagement94jpg, height: 500, width: 333 },
    SamanthaShawnEngagement96jpg: { src: SamanthaShawnEngagement96jpg, height: 500, width: 333 },
    SamanthaShawnEngagement97jpg: { src: SamanthaShawnEngagement97jpg, height: 500, width: 333 },
    SamanthaShawnEngagement98jpg: { src: SamanthaShawnEngagement98jpg, height: 500, width: 333 }
};
