import * as photo_SamanthaShawnEngagement15jpg from './Samantha + Shawn Engagement-15.jpg';
import * as photo_SamanthaShawnEngagement18jpg from './Samantha + Shawn Engagement-18.jpg';
import * as photo_SamanthaShawnEngagement34jpg from './Samantha + Shawn Engagement-34.jpg';
import * as photo_SamanthaShawnEngagement49jpg from './Samantha + Shawn Engagement-49.jpg';
import * as photo_SamanthaShawnEngagement5jpg from './Samantha + Shawn Engagement-5.jpg';
import * as photo_SamanthaShawnEngagement50jpg from './Samantha + Shawn Engagement-50.jpg';
import * as photo_SamanthaShawnEngagement51jpg from './Samantha + Shawn Engagement-51.jpg';
import * as photo_SamanthaShawnEngagement52jpg from './Samantha + Shawn Engagement-52.jpg';
import * as photo_SamanthaShawnEngagement53jpg from './Samantha + Shawn Engagement-53.jpg';
import * as photo_SamanthaShawnEngagement54jpg from './Samantha + Shawn Engagement-54.jpg';
import * as photo_SamanthaShawnEngagement55jpg from './Samantha + Shawn Engagement-55.jpg';
import * as photo_SamanthaShawnEngagement56jpg from './Samantha + Shawn Engagement-56.jpg';
import * as photo_SamanthaShawnEngagement57jpg from './Samantha + Shawn Engagement-57.jpg';
import * as photo_SamanthaShawnEngagement58jpg from './Samantha + Shawn Engagement-58.jpg';
import * as photo_SamanthaShawnEngagement59jpg from './Samantha + Shawn Engagement-59.jpg';
import * as photo_SamanthaShawnEngagement6jpg from './Samantha + Shawn Engagement-6.jpg';
import * as photo_SamanthaShawnEngagement60jpg from './Samantha + Shawn Engagement-60.jpg';
import * as photo_SamanthaShawnEngagement61jpg from './Samantha + Shawn Engagement-61.jpg';
import * as photo_SamanthaShawnEngagement62jpg from './Samantha + Shawn Engagement-62.jpg';
import * as photo_SamanthaShawnEngagement63jpg from './Samantha + Shawn Engagement-63.jpg';
import * as photo_SamanthaShawnEngagement65jpg from './Samantha + Shawn Engagement-65.jpg';
import * as photo_SamanthaShawnEngagement66jpg from './Samantha + Shawn Engagement-66.jpg';
import * as photo_SamanthaShawnEngagement67jpg from './Samantha + Shawn Engagement-67.jpg';
import * as photo_SamanthaShawnEngagement68jpg from './Samantha + Shawn Engagement-68.jpg';
import * as photo_SamanthaShawnEngagement69jpg from './Samantha + Shawn Engagement-69.jpg';
import * as photo_SamanthaShawnEngagement7jpg from './Samantha + Shawn Engagement-7.jpg';
import * as photo_SamanthaShawnEngagement70jpg from './Samantha + Shawn Engagement-70.jpg';
import * as photo_SamanthaShawnEngagement71jpg from './Samantha + Shawn Engagement-71.jpg';
import * as photo_SamanthaShawnEngagement72jpg from './Samantha + Shawn Engagement-72.jpg';
import * as photo_SamanthaShawnEngagement73jpg from './Samantha + Shawn Engagement-73.jpg';
import * as photo_SamanthaShawnEngagement74jpg from './Samantha + Shawn Engagement-74.jpg';
import * as photo_SamanthaShawnEngagement75jpg from './Samantha + Shawn Engagement-75.jpg';
import * as photo_SamanthaShawnEngagement76jpg from './Samantha + Shawn Engagement-76.jpg';
import * as photo_SamanthaShawnEngagement77jpg from './Samantha + Shawn Engagement-77.jpg';
import * as photo_SamanthaShawnEngagement78jpg from './Samantha + Shawn Engagement-78.jpg';
import * as photo_SamanthaShawnEngagement79jpg from './Samantha + Shawn Engagement-79.jpg';
import * as photo_SamanthaShawnEngagement8jpg from './Samantha + Shawn Engagement-8.jpg';
import * as photo_SamanthaShawnEngagement80jpg from './Samantha + Shawn Engagement-80.jpg';
import * as photo_SamanthaShawnEngagement81jpg from './Samantha + Shawn Engagement-81.jpg';
import * as photo_SamanthaShawnEngagement82jpg from './Samantha + Shawn Engagement-82.jpg';
import * as photo_SamanthaShawnEngagement83jpg from './Samantha + Shawn Engagement-83.jpg';
import * as photo_SamanthaShawnEngagement84jpg from './Samantha + Shawn Engagement-84.jpg';
import * as photo_SamanthaShawnEngagement85jpg from './Samantha + Shawn Engagement-85.jpg';
import * as photo_SamanthaShawnEngagement86jpg from './Samantha + Shawn Engagement-86.jpg';
import * as photo_SamanthaShawnEngagement87jpg from './Samantha + Shawn Engagement-87.jpg';
import * as photo_SamanthaShawnEngagement88jpg from './Samantha + Shawn Engagement-88.jpg';
import * as photo_SamanthaShawnEngagement89jpg from './Samantha + Shawn Engagement-89.jpg';
import * as photo_SamanthaShawnEngagement9jpg from './Samantha + Shawn Engagement-9.jpg';
import * as photo_SamanthaShawnEngagement90jpg from './Samantha + Shawn Engagement-90.jpg';
import * as photo_SamanthaShawnEngagement91jpg from './Samantha + Shawn Engagement-91.jpg';
import * as photo_SamanthaShawnEngagement92jpg from './Samantha + Shawn Engagement-92.jpg';
import * as photo_SamanthaShawnEngagement93jpg from './Samantha + Shawn Engagement-93.jpg';
import * as photo_SamanthaShawnEngagement94jpg from './Samantha + Shawn Engagement-94.jpg';
import * as photo_SamanthaShawnEngagement96jpg from './Samantha + Shawn Engagement-96.jpg';
import * as photo_SamanthaShawnEngagement97jpg from './Samantha + Shawn Engagement-97.jpg';
import * as photo_SamanthaShawnEngagement98jpg from './Samantha + Shawn Engagement-98.jpg';

/**
 * Collection of engagement photos
 */
export const EngagementPhotos: { [key: string]: { src: string; height: number; width: number } } = {
    photo_SamanthaShawnEngagement15jpg: { src: photo_SamanthaShawnEngagement15jpg, height: 500, width: 333 },
    photo_SamanthaShawnEngagement18jpg: { src: photo_SamanthaShawnEngagement18jpg, height: 500, width: 333 },
    photo_SamanthaShawnEngagement34jpg: { src: photo_SamanthaShawnEngagement34jpg, height: 500, width: 333 },
    photo_SamanthaShawnEngagement49jpg: { src: photo_SamanthaShawnEngagement49jpg, height: 500, width: 750 },
    photo_SamanthaShawnEngagement5jpg: { src: photo_SamanthaShawnEngagement5jpg, height: 500, width: 333 },
    photo_SamanthaShawnEngagement50jpg: { src: photo_SamanthaShawnEngagement50jpg, height: 500, width: 750 },
    photo_SamanthaShawnEngagement51jpg: { src: photo_SamanthaShawnEngagement51jpg, height: 500, width: 749 },
    photo_SamanthaShawnEngagement52jpg: { src: photo_SamanthaShawnEngagement52jpg, height: 500, width: 749 },
    photo_SamanthaShawnEngagement53jpg: { src: photo_SamanthaShawnEngagement53jpg, height: 500, width: 749 },
    photo_SamanthaShawnEngagement54jpg: { src: photo_SamanthaShawnEngagement54jpg, height: 500, width: 749 },
    photo_SamanthaShawnEngagement55jpg: { src: photo_SamanthaShawnEngagement55jpg, height: 500, width: 749 },
    photo_SamanthaShawnEngagement56jpg: { src: photo_SamanthaShawnEngagement56jpg, height: 500, width: 749 },
    photo_SamanthaShawnEngagement57jpg: { src: photo_SamanthaShawnEngagement57jpg, height: 500, width: 749 },
    photo_SamanthaShawnEngagement58jpg: { src: photo_SamanthaShawnEngagement58jpg, height: 500, width: 333 },
    photo_SamanthaShawnEngagement59jpg: { src: photo_SamanthaShawnEngagement59jpg, height: 500, width: 333 },
    photo_SamanthaShawnEngagement6jpg: { src: photo_SamanthaShawnEngagement6jpg, height: 500, width: 749 },
    photo_SamanthaShawnEngagement60jpg: { src: photo_SamanthaShawnEngagement60jpg, height: 500, width: 333 },
    photo_SamanthaShawnEngagement61jpg: { src: photo_SamanthaShawnEngagement61jpg, height: 500, width: 333 },
    photo_SamanthaShawnEngagement62jpg: { src: photo_SamanthaShawnEngagement62jpg, height: 500, width: 333 },
    photo_SamanthaShawnEngagement63jpg: { src: photo_SamanthaShawnEngagement63jpg, height: 500, width: 333 },
    photo_SamanthaShawnEngagement65jpg: { src: photo_SamanthaShawnEngagement65jpg, height: 500, width: 333 },
    photo_SamanthaShawnEngagement66jpg: { src: photo_SamanthaShawnEngagement66jpg, height: 500, width: 749 },
    photo_SamanthaShawnEngagement67jpg: { src: photo_SamanthaShawnEngagement67jpg, height: 500, width: 749 },
    photo_SamanthaShawnEngagement68jpg: { src: photo_SamanthaShawnEngagement68jpg, height: 500, width: 749 },
    photo_SamanthaShawnEngagement69jpg: { src: photo_SamanthaShawnEngagement69jpg, height: 500, width: 749 },
    photo_SamanthaShawnEngagement7jpg: { src: photo_SamanthaShawnEngagement7jpg, height: 500, width: 749 },
    photo_SamanthaShawnEngagement70jpg: { src: photo_SamanthaShawnEngagement70jpg, height: 500, width: 749 },
    photo_SamanthaShawnEngagement71jpg: { src: photo_SamanthaShawnEngagement71jpg, height: 500, width: 749 },
    photo_SamanthaShawnEngagement72jpg: { src: photo_SamanthaShawnEngagement72jpg, height: 500, width: 749 },
    photo_SamanthaShawnEngagement73jpg: { src: photo_SamanthaShawnEngagement73jpg, height: 500, width: 749 },
    photo_SamanthaShawnEngagement74jpg: { src: photo_SamanthaShawnEngagement74jpg, height: 500, width: 749 },
    photo_SamanthaShawnEngagement75jpg: { src: photo_SamanthaShawnEngagement75jpg, height: 500, width: 749 },
    photo_SamanthaShawnEngagement76jpg: { src: photo_SamanthaShawnEngagement76jpg, height: 500, width: 333 },
    photo_SamanthaShawnEngagement77jpg: { src: photo_SamanthaShawnEngagement77jpg, height: 500, width: 333 },
    photo_SamanthaShawnEngagement78jpg: { src: photo_SamanthaShawnEngagement78jpg, height: 500, width: 333 },
    photo_SamanthaShawnEngagement79jpg: { src: photo_SamanthaShawnEngagement79jpg, height: 500, width: 333 },
    photo_SamanthaShawnEngagement8jpg: { src: photo_SamanthaShawnEngagement8jpg, height: 500, width: 749 },
    photo_SamanthaShawnEngagement80jpg: { src: photo_SamanthaShawnEngagement80jpg, height: 500, width: 333 },
    photo_SamanthaShawnEngagement81jpg: { src: photo_SamanthaShawnEngagement81jpg, height: 500, width: 333 },
    photo_SamanthaShawnEngagement82jpg: { src: photo_SamanthaShawnEngagement82jpg, height: 500, width: 749 },
    photo_SamanthaShawnEngagement83jpg: { src: photo_SamanthaShawnEngagement83jpg, height: 500, width: 749 },
    photo_SamanthaShawnEngagement84jpg: { src: photo_SamanthaShawnEngagement84jpg, height: 500, width: 749 },
    photo_SamanthaShawnEngagement85jpg: { src: photo_SamanthaShawnEngagement85jpg, height: 500, width: 749 },
    photo_SamanthaShawnEngagement86jpg: { src: photo_SamanthaShawnEngagement86jpg, height: 500, width: 749 },
    photo_SamanthaShawnEngagement87jpg: { src: photo_SamanthaShawnEngagement87jpg, height: 500, width: 749 },
    photo_SamanthaShawnEngagement88jpg: { src: photo_SamanthaShawnEngagement88jpg, height: 500, width: 749 },
    photo_SamanthaShawnEngagement89jpg: { src: photo_SamanthaShawnEngagement89jpg, height: 500, width: 749 },
    photo_SamanthaShawnEngagement9jpg: { src: photo_SamanthaShawnEngagement9jpg, height: 500, width: 333 },
    photo_SamanthaShawnEngagement90jpg: { src: photo_SamanthaShawnEngagement90jpg, height: 500, width: 749 },
    photo_SamanthaShawnEngagement91jpg: { src: photo_SamanthaShawnEngagement91jpg, height: 500, width: 749 },
    photo_SamanthaShawnEngagement92jpg: { src: photo_SamanthaShawnEngagement92jpg, height: 500, width: 333 },
    photo_SamanthaShawnEngagement93jpg: { src: photo_SamanthaShawnEngagement93jpg, height: 500, width: 333 },
    photo_SamanthaShawnEngagement94jpg: { src: photo_SamanthaShawnEngagement94jpg, height: 500, width: 333 },
    photo_SamanthaShawnEngagement96jpg: { src: photo_SamanthaShawnEngagement96jpg, height: 500, width: 333 },
    photo_SamanthaShawnEngagement97jpg: { src: photo_SamanthaShawnEngagement97jpg, height: 500, width: 333 },
    photo_SamanthaShawnEngagement98jpg: { src: photo_SamanthaShawnEngagement98jpg, height: 500, width: 333 }
};
